# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

InvMat_Rcpp <- function(input) {
    .Call('_GKF_InvMat_Rcpp', PACKAGE = 'GKF', input)
}

nearPD_Rcpp <- function(x, w, corr, keepDiag, EnforcePosDef, doSym, ensureSymmetry, eig_tol, conv_tol, posd_tol, maxit, chol) {
    .Call('_GKF_nearPD_Rcpp', PACKAGE = 'GKF', x, w, corr, keepDiag, EnforcePosDef, doSym, ensureSymmetry, eig_tol, conv_tol, posd_tol, maxit, chol)
}

Robust_chol_Rcpp <- function(B, eig_tol = 0.001) {
    .Call('_GKF_Robust_chol_Rcpp', PACKAGE = 'GKF', B, eig_tol)
}

FKF <- function(a0_, P0_, dt_, ct_, Tt_, Zt_, Ht_, Qt_, yt_, ComputeThetaLik = FALSE, ThetaVal = 0L) {
    .Call('_GKF_FKF', PACKAGE = 'GKF', a0_, P0_, dt_, ct_, Tt_, Zt_, Ht_, Qt_, yt_, ComputeThetaLik, ThetaVal)
}

NRUpdatingStep <- function(a0_, P0_, dt_, ct_, Tt_, Zt_, Ht_, Qt_, yt_) {
    .Call('_GKF_NRUpdatingStep', PACKAGE = 'GKF', a0_, P0_, dt_, ct_, Tt_, Zt_, Ht_, Qt_, yt_)
}

thetaSampling <- function(a0_, P0_, dt_, ct_, Tt_, Zt_, Ht_, Qt_, yt_, thetaHat_, M) {
    .Call('_GKF_thetaSampling', PACKAGE = 'GKF', a0_, P0_, dt_, ct_, Tt_, Zt_, Ht_, Qt_, yt_, thetaHat_, M)
}

GaussianSignalSmoothing <- function(a0_, P0_, dt_, ct_, Tt_, Zt_, Ht_, Qt_, yt_) {
    .Call('_GKF_GaussianSignalSmoothing', PACKAGE = 'GKF', a0_, P0_, dt_, ct_, Tt_, Zt_, Ht_, Qt_, yt_)
}

GaussianthetaSampling <- function(a0_, P0_, dt_, ct_, Tt_, Zt_, Ht_, Qt_, yt_, M) {
    .Call('_GKF_GaussianthetaSampling', PACKAGE = 'GKF', a0_, P0_, dt_, ct_, Tt_, Zt_, Ht_, Qt_, yt_, M)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_GKF_RcppExport_registerCCallable', PACKAGE = 'GKF')
})
